### ISSUE TITLE
Error: M2: Accessory LTPK not yet set

### ISSUE THREAD

**Issue by minamoanes** [Apollon77/hap-controller-node#184]
**Describe the bug**  
Hey @Apollon77, would be great if you could take a look at this issue here: https://github.com/minamoanes/homebridge-homekit-control/issues/3

Am I doing something wrong with the configuration?
Thank you so much!

**Comment by Apollon77** [comment]
Please give some more guidance. Which part of your code is affected? Link please ideally.  And I need a full debug log with "DEBUG=hapcontroller" as stated in the readme, else I would just guess around.

is it wjhile pairing or is it to connect to the devcie AFTER pairing? The error is on the pair verigfy party, so it should be second case, so please make sure that the pairing data were correctly stored and initialized BEFORE trying to connect because this message more or less says that part of the "pairing dat" are not set.

Start there and make sure that all this works as expected! If you need more suppoirt please provide a full log
